import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { withMermaid } from 'vitepress-plugin-mermaid';

// Generated by `bun run docs:api` (typedoc + typedoc-vitepress-theme) before
// this config loads — docs:dev/docs:build always run docs:api first.
const typedocSidebarPath = fileURLToPath(new URL('../api/typedoc-sidebar.json', import.meta.url));
const typedocSidebar = JSON.parse(readFileSync(typedocSidebarPath, 'utf-8'));

const guideSidebar = [
  {
    text: 'Guide',
    items: [
      { text: 'Getting Started', link: '/guide/getting-started' },
      { text: 'Mini-Notation', link: '/guide/mini-notation' },
      { text: 'Tempo & Note Length', link: '/guide/tempo-and-note-length' },
      { text: 'Melody & Harmony', link: '/guide/melody-and-harmony' },
      { text: 'Samples', link: '/guide/samples' },
      { text: 'Effects & Filters', link: '/guide/effects' },
      { text: 'Patterned Parameters', link: '/guide/patterned-parameters' },
      { text: 'Arranging Songs', link: '/guide/arranging-songs' },
      { text: 'Stereo & Surround', link: '/guide/stereo-and-surround' },
      { text: 'Troubleshooting', link: '/guide/troubleshooting' }
    ]
  },
  {
    text: 'More',
    items: [
      { text: 'Recipes', link: '/recipes' },
      { text: 'Coming from Strudel', link: '/coming-from-strudel' }
    ]
  }
];

const base = '/undertone/';

export default withMermaid({
  title: 'undertone',
  description: 'A procedural synth engine for games and music, built on the Web Audio API.',
  base,
  cleanUrls: true,
  // Absolute, not `favicon.svg` — a bare relative href resolves against the
  // *current page's* URL, so it'd 404 from anywhere but the site root (the
  // same bug the Playground nav link had).
  head: [['link', { rel: 'icon', type: 'image/svg+xml', href: `${base}favicon.svg` }]],
  // The guide's effects/arrange pages embed Mermaid diagrams as fenced ```mermaid blocks.
  mermaid: {},
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Recipes', link: '/recipes' },
      { text: 'Coming from Strudel', link: '/coming-from-strudel' },
      { text: 'API', link: '/api/' },
      { text: 'Playground', link: '/playground' }
    ],
    sidebar: {
      '/guide/': guideSidebar,
      '/recipes': guideSidebar,
      '/coming-from-strudel': guideSidebar,
      '/api/': typedocSidebar
    },
    search: {
      provider: 'local'
    },
    // The dedicated icon slot, rather than a plain nav-text item — shaves one
    // item off the inline text menu (see custom.css's nav-overflow note) and
    // is the idiomatic place for a repo link.
    socialLinks: [{ icon: 'github', link: 'https://github.com/liminal-hq/undertone' }]
  }
});
