import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitepress';

// Generated by `bun run docs:api` (typedoc + typedoc-vitepress-theme) before
// this config loads — docs:dev/docs:build always run docs:api first.
const typedocSidebarPath = fileURLToPath(new URL('../api/typedoc-sidebar.json', import.meta.url));
const typedocSidebar = JSON.parse(readFileSync(typedocSidebarPath, 'utf-8'));

const guideSidebar = [
  {
    text: 'Guide',
    items: [
      { text: 'Getting Started', link: '/guide/getting-started' },
      { text: 'Mini-Notation', link: '/guide/mini-notation' },
      { text: 'Tempo & Note Length', link: '/guide/tempo-and-note-length' },
      { text: 'Melody & Harmony', link: '/guide/melody-and-harmony' },
      { text: 'Samples', link: '/guide/samples' },
      { text: 'Effects & Filters', link: '/guide/effects' },
      { text: 'Patterned Parameters', link: '/guide/patterned-parameters' },
      { text: 'Arranging Songs', link: '/guide/arranging-songs' },
      { text: 'Stereo & Surround', link: '/guide/stereo-and-surround' },
      { text: 'Troubleshooting', link: '/guide/troubleshooting' }
    ]
  },
  {
    text: 'More',
    items: [
      { text: 'Recipes', link: '/recipes' },
      { text: 'Coming from Strudel', link: '/coming-from-strudel' }
    ]
  }
];

export default defineConfig({
  title: 'undertone',
  description: 'A procedural synth engine for games and music, built on the Web Audio API.',
  base: '/undertone/docs/',
  cleanUrls: true,
  markdown: {
    // The guide's effects/arrange pages embed Mermaid diagrams as fenced ```mermaid blocks.
    mermaid: true
  },
  themeConfig: {
    nav: [
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'Recipes', link: '/recipes' },
      { text: 'Coming from Strudel', link: '/coming-from-strudel' },
      { text: 'API', link: '/api/' },
      { text: 'Playground', link: '../' },
      { text: 'GitHub', link: 'https://github.com/liminal-hq/undertone' }
    ],
    sidebar: {
      '/guide/': guideSidebar,
      '/recipes': guideSidebar,
      '/coming-from-strudel': guideSidebar,
      '/api/': typedocSidebar
    },
    search: {
      provider: 'local'
    }
  }
});
